#!/usr/bin/env python3
"""DPO fine-tuning for ACORD form extraction using TRL DPOTrainer.

Loads an SFT checkpoint (from train.py) as starting point, then applies
Direct Preference Optimization using preference pairs generated by
build_preference_pairs.py.

Prerequisites:
    uv pip install unsloth bitsandbytes trl

Usage:
    .venv/bin/python finetune/train_dpo.py
    .venv/bin/python finetune/train_dpo.py --sft-checkpoint finetune/output/final --beta 0.1
"""

import argparse
import json
import os
import sys
from pathlib import Path

from torch.utils.data import Dataset as TorchDataset
from PIL import Image

# ── Configuration ──────────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "finetune" / "data"
OUTPUT_DIR = ROOT / "finetune" / "output"
DEFAULT_SFT_CHECKPOINT = OUTPUT_DIR / "final"

MODEL_MAP = {
    "3b": "unsloth/Qwen2.5-VL-3B-Instruct-bnb-4bit",
    "7b": "unsloth/Qwen2.5-VL-7B-Instruct-bnb-4bit",
}


class DPOPreferenceDataset(TorchDataset):
    """PyTorch Dataset for DPO preference pairs.

    Each example has chosen/rejected conversation pairs and associated images.
    """

    def __init__(self, jsonl_path: Path):
        self.examples = []
        with open(jsonl_path) as f:
            for line in f:
                line = line.strip()
                if line:
                    self.examples.append(json.loads(line))

    def __len__(self):
        return len(self.examples)

    def __getitem__(self, idx):
        ex = self.examples[idx]
        # Load images as PIL
        images = []
        for p in ex.get("images", []):
            if os.path.exists(p):
                images.append(Image.open(p).convert("RGB"))
            else:
                print(f"  WARNING: Image not found: {p}", file=sys.stderr)

        return {
            "chosen": ex["chosen"],
            "rejected": ex["rejected"],
            "images": images,
        }


def parse_args():
    parser = argparse.ArgumentParser(description="DPO fine-tuning for ACORD extraction")
    parser.add_argument(
        "--sft-checkpoint", type=Path, default=DEFAULT_SFT_CHECKPOINT,
        help=f"SFT checkpoint to start from (default: {DEFAULT_SFT_CHECKPOINT})",
    )
    parser.add_argument(
        "--preference-data", type=Path, default=DATA_DIR / "preference_pairs.jsonl",
        help="Preference pairs JSONL file (default: finetune/data/preference_pairs.jsonl)",
    )
    parser.add_argument(
        "--model", choices=["3b", "7b"], default="7b",
        help="Base model size — must match SFT checkpoint (default: 7b)",
    )
    parser.add_argument("--beta", type=float, default=0.1, help="DPO beta parameter (default: 0.1)")
    parser.add_argument("--lr", type=float, default=5e-7, help="Learning rate (default: 5e-7)")
    parser.add_argument("--epochs", type=int, default=1, help="Training epochs (default: 1)")
    parser.add_argument("--batch-size", type=int, default=1, help="Per-device batch size (default: 1)")
    parser.add_argument("--grad-accum", type=int, default=4, help="Gradient accumulation steps (default: 4)")
    parser.add_argument("--max-seq-len", type=int, default=4096, help="Max sequence length (default: 4096)")
    parser.add_argument("--seed", type=int, default=42, help="Random seed (default: 42)")
    return parser.parse_args()


def main():
    args = parse_args()

    # ── Validate data exists ──
    if not args.preference_data.exists():
        print(f"ERROR: Preference data not found: {args.preference_data}")
        print("  Run build_preference_pairs.py first.")
        sys.exit(1)

    # ── Load preference dataset ──
    print("Loading preference dataset...")
    dataset = DPOPreferenceDataset(args.preference_data)
    print(f"  Preference pairs: {len(dataset)}")

    if len(dataset) == 0:
        print("ERROR: No preference pairs found")
        sys.exit(1)

    # ── Load model with SFT checkpoint ──
    sft_path = args.sft_checkpoint
    if sft_path.exists():
        print(f"\nLoading SFT checkpoint from {sft_path}...")
        model_name = str(sft_path)
    else:
        print(f"WARNING: SFT checkpoint not found at {sft_path}")
        print(f"  Falling back to base model: {MODEL_MAP[args.model]}")
        model_name = MODEL_MAP[args.model]

    from unsloth import FastVisionModel
    from unsloth.trainer import is_bfloat16_supported

    model, tokenizer = FastVisionModel.from_pretrained(
        model_name,
        max_seq_length=args.max_seq_len,
        load_in_4bit=True,
        use_gradient_checkpointing="unsloth",
    )

    # Apply LoRA if loading from base model (SFT checkpoint already has LoRA)
    if not sft_path.exists():
        print("Applying LoRA adapters...")
        model = FastVisionModel.get_peft_model(
            model,
            r=16,
            lora_alpha=32,
            lora_dropout=0.05,
            target_modules=[
                "q_proj", "k_proj", "v_proj", "o_proj",
                "gate_proj", "up_proj", "down_proj",
            ],
            bias="none",
            use_rslora=False,
            finetune_vision_layers=True,
            finetune_language_layers=True,
            finetune_attention_modules=True,
            finetune_mlp_modules=True,
        )

    # ── Load processor for DPO (needs ProcessorMixin) ──
    from transformers import AutoProcessor
    processor = AutoProcessor.from_pretrained(
        MODEL_MAP[args.model].replace("unsloth/", "Qwen/").replace("-bnb-4bit", ""),
    )

    # ── Configure DPO training ──
    dpo_output_dir = OUTPUT_DIR / "dpo"
    dpo_output_dir.mkdir(parents=True, exist_ok=True)

    from trl import DPOConfig, DPOTrainer

    training_args = DPOConfig(
        output_dir=str(dpo_output_dir),
        per_device_train_batch_size=args.batch_size,
        gradient_accumulation_steps=args.grad_accum,
        learning_rate=args.lr,
        num_train_epochs=args.epochs,
        beta=args.beta,
        lr_scheduler_type="cosine",
        optim="adamw_8bit",
        weight_decay=0.01,
        fp16=not is_bfloat16_supported(),
        bf16=is_bfloat16_supported(),
        logging_steps=1,
        save_strategy="epoch",
        save_total_limit=2,
        seed=args.seed,
        max_length=args.max_seq_len,
        max_prompt_length=args.max_seq_len // 2,
        report_to="none",
        remove_unused_columns=False,
    )

    # ── Create DPO trainer ──
    # ref_model=None: PEFT adapter switching handles reference model
    trainer = DPOTrainer(
        model=model,
        ref_model=None,
        args=training_args,
        train_dataset=dataset,
        processing_class=processor,
    )

    # ── Train ──
    print(f"\nStarting DPO training:")
    print(f"  SFT checkpoint: {sft_path}")
    print(f"  Beta:           {args.beta}")
    print(f"  Epochs:         {args.epochs}")
    print(f"  Batch:          {args.batch_size} x {args.grad_accum} grad accum")
    print(f"  LR:             {args.lr}")
    print(f"  Pairs:          {len(dataset)}")
    print(f"  Output:         {dpo_output_dir}")
    print()

    trainer.train()

    # ── Save final model ──
    final_dir = dpo_output_dir / "final"
    print(f"\nSaving DPO model to {final_dir}...")
    model.save_pretrained(str(final_dir))
    tokenizer.save_pretrained(str(final_dir))

    print("\nDPO training complete!")
    print(f"  Model saved to: {final_dir}")
    print(f"  Next step: python finetune/export_ollama.py --lora-dir {final_dir}")


if __name__ == "__main__":
    main()
