"""Node functions for the LangGraph intake agent."""

import json
import logging

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI

from Custom_model_fa_pf.agent.state import IntakePhase, IntakeState
from Custom_model_fa_pf.agent.prompts import (
    build_system_message,
    build_form_state_context,
    REFLECTION_PROMPT,
    SUMMARIZE_PROMPT,
)
from Custom_model_fa_pf.config import (
    LLM_BACKEND,
    VLLM_BASE_URL,
    OLLAMA_OPENAI_URL,
    AGENT_MODEL,
    AGENT_TEMPERATURE,
    AGENT_MAX_TOKENS,
    SUMMARIZE_AFTER_TURNS,
)

logger = logging.getLogger(__name__)


def _get_chat_llm() -> ChatOpenAI:
    """Create a ChatOpenAI instance for node-level LLM calls (reflect, summarize)."""
    base_url = VLLM_BASE_URL if LLM_BACKEND == "vllm" else OLLAMA_OPENAI_URL
    return ChatOpenAI(
        base_url=base_url,
        api_key="not-needed",
        model=AGENT_MODEL,
        temperature=AGENT_TEMPERATURE,
        max_tokens=AGENT_MAX_TOKENS,
    )


def greet_node(state: IntakeState) -> dict:
    """Welcome the customer and initiate the intake conversation."""
    greeting = (
        "Welcome! I'm here to help you with your commercial insurance application. "
        "I'll walk you through the process step by step.\n\n"
        "To get started, could you tell me your business name and what type of "
        "business you operate?"
    )
    return {
        "messages": [AIMessage(content=greeting)],
        "phase": IntakePhase.APPLICANT_INFO.value,
        "conversation_turn": state.get("conversation_turn", 0) + 1,
    }


def understand_node(state: IntakeState) -> dict:
    """Process the latest user message — extract entities and update state.

    This node reads the latest user message and updates form_state with
    any new information. It does NOT call the LLM directly — it uses
    the tool results that come back from the agent's tool calls.
    """
    # The understanding happens via tool calls in the agent node.
    # This node simply increments the conversation turn.
    return {
        "conversation_turn": state.get("conversation_turn", 0) + 1,
    }


def check_gaps_node(state: IntakeState) -> dict:
    """Analyze completeness and decide what to do next.

    This is a routing node — it doesn't modify state, just evaluates it.
    The actual routing decision is made by route_after_gaps().
    """
    form_state = state.get("form_state", {})
    confirmed = sum(1 for f in form_state.values() if f.get("status") == "confirmed")
    total_expected = len(form_state) if form_state else 0

    logger.debug(f"Gap check: {confirmed}/{total_expected} fields confirmed, phase={state.get('phase')}")
    return {}  # Pure routing node — route_after_gaps does the logic


def route_after_gaps(state: IntakeState) -> str:
    """Conditional routing after gap analysis.

    Returns:
        "respond" — need more info, generate a follow-up question
        "validate" — have enough info, run validation
        "review" — all complete, show summary
    """
    phase = state.get("phase", IntakePhase.GREETING.value)

    # If we're in REVIEW phase, go to review
    if phase == IntakePhase.REVIEW.value:
        return "review"

    # If we're in COMPLETE phase, also go to review
    if phase == IntakePhase.COMPLETE.value:
        return "review"

    # Check if we have enough data to validate
    form_state = state.get("form_state", {})
    entities = state.get("entities", {})
    lobs = state.get("lobs", [])
    assigned_forms = state.get("assigned_forms", [])

    # If we have LOBs + assigned forms + substantial entities, try validation
    confirmed_count = sum(1 for f in form_state.values() if f.get("status") == "confirmed")
    has_lobs = len(lobs) > 0
    has_forms = len(assigned_forms) > 0
    has_entities = bool(entities.get("business", {}).get("business_name"))

    if has_lobs and has_forms and has_entities and confirmed_count >= 10:
        # Check validation issues
        issues = state.get("validation_issues", [])
        errors = [i for i in issues if i.get("severity") == "error"]
        if not errors:
            return "review"
        return "validate"

    # Default: need more info
    return "respond"


def respond_node(state: IntakeState) -> dict:
    """This is a placeholder — the actual response is generated by the LLM agent node.

    In the compiled graph, the agent node (with tool calling) handles response
    generation. This node is used as a pass-through for the routing logic.
    """
    return {}


def validate_node(state: IntakeState) -> dict:
    """Run validation on all collected field values."""
    from Custom_model_fa_pf.validation_engine import validate

    form_state = state.get("form_state", {})
    # Build a flat dict of field_name -> value for validation
    fields = {k: v.get("value", "") for k, v in form_state.items() if v.get("value")}

    if not fields:
        return {"validation_issues": []}

    result = validate(fields)
    issues = [issue.to_dict() for issue in result.issues]

    # Apply auto-corrections back to form_state
    updated_state = dict(form_state)
    for field_name, corrected_value in result.auto_corrections.items():
        if field_name in updated_state:
            updated_state[field_name] = {
                **updated_state[field_name],
                "value": result.corrected_values.get(field_name, updated_state[field_name].get("value")),
                "status": "confirmed",
            }

    return {
        "validation_issues": issues,
        "form_state": updated_state,
    }


def review_node(state: IntakeState) -> dict:
    """Generate a summary of all collected information for customer confirmation."""
    form_state = state.get("form_state", {})
    confirmed = {k: v for k, v in form_state.items() if v.get("status") == "confirmed"}

    lines = ["Here's a summary of everything I've collected:\n"]
    for field_name, info in sorted(confirmed.items()):
        lines.append(f"  - {field_name}: {info.get('value', '')}")

    issues = state.get("validation_issues", [])
    if issues:
        lines.append(f"\nValidation notes ({len(issues)}):")
        for issue in issues[:5]:
            lines.append(f"  - {issue.get('message', '')}")

    lines.append("\nDoes everything look correct? Let me know if you'd like to change anything.")

    return {
        "messages": [AIMessage(content="\n".join(lines))],
        "phase": IntakePhase.COMPLETE.value,
    }


def reflect_node(state: IntakeState) -> dict:
    """Critique the agent's last response before showing to user (Pattern 4: Reflection).

    Checks for hallucination, multiple questions, off-topic content, and incorrect
    confirmations. If issues found, sends revision feedback back to agent.
    """
    messages = state.get("messages", [])
    if not messages:
        return {}

    last = messages[-1]
    # Only reflect on AI text responses, not tool calls or empty messages
    if not isinstance(last, AIMessage) or not last.content:
        return {}
    if getattr(last, "tool_calls", None):
        return {}  # Don't reflect on tool-calling messages

    llm = _get_chat_llm()
    prompt = REFLECTION_PROMPT.format(
        response=last.content,
        form_state_summary=build_form_state_context(state.get("form_state", {})),
    )

    try:
        result = llm.invoke([SystemMessage(content=prompt)])
        verdict = json.loads(result.content)
        if verdict.get("verdict") == "pass":
            logger.debug("Reflection passed for response")
            return {}  # Response is fine, pass through

        # Response needs revision — increment reflect_count and add feedback
        issues = verdict.get("issues", [])
        suggestion = verdict.get("suggestion", "Please revise your response.")
        logger.info("Reflection flagged issues: %s", issues)
        return {
            "messages": [SystemMessage(content=f"REVISION NEEDED: {suggestion}")],
            "reflect_count": state.get("reflect_count", 0) + 1,
        }
    except (json.JSONDecodeError, Exception) as exc:
        logger.debug("Reflection failed (letting response through): %s", exc)
        return {}  # Reflection failed — let the response through


def summarize_node(state: IntakeState) -> dict:
    """Compress old messages into a summary when conversation gets long (Pattern 8: Memory).

    Keeps the last 6 messages for immediate context, summarizes everything else.
    Uses RemoveMessage to prune old messages from the add_messages reducer.
    """
    messages = state.get("messages", [])
    turn = state.get("conversation_turn", 0)

    if turn < SUMMARIZE_AFTER_TURNS or len(messages) < 20:
        return {}  # Not enough history to warrant summarization

    # Keep the last 6 messages for immediate context
    to_summarize = messages[:-6]
    if not to_summarize:
        return {}

    # Build conversation text from messages to summarize
    conversation_text = "\n".join(
        f"{'User' if isinstance(m, HumanMessage) else 'Agent'}: {m.content}"
        for m in to_summarize
        if isinstance(m, (HumanMessage, AIMessage)) and m.content
    )

    if not conversation_text.strip():
        return {}

    llm = _get_chat_llm()
    prompt = SUMMARIZE_PROMPT.format(
        conversation_text=conversation_text,
        form_state_summary=build_form_state_context(state.get("form_state", {})),
    )

    try:
        result = llm.invoke([SystemMessage(content=prompt)])
        new_summary = result.content.strip()
        logger.info(
            "Summarized %d messages into %d chars",
            len(to_summarize), len(new_summary),
        )
    except Exception as exc:
        logger.warning("Summarization failed: %s", exc)
        return {}  # Summarization failed — keep full history

    # Use RemoveMessage to prune old messages from the state
    from langgraph.graph.message import RemoveMessage
    removals = [
        RemoveMessage(id=m.id)
        for m in to_summarize
        if hasattr(m, "id") and m.id
    ]

    return {
        "summary": new_summary,
        "messages": removals,  # add_messages reducer handles RemoveMessage
    }
